### ISSUE TITLE
float64 data wire format documentation is incorrect

### ISSUE THREAD

**Issue by BD103** [edgedb/website#11]
[In `float64`'s data wire documentation](https://www.edgedb.com/docs/reference/protocol/dataformats#std-float64), the link goes to `std::float32` and not `std::float64`. Other pieces of information for `float64` is wrong as well. I think it was copied from `float32` without the information being changed.

<img width="1552" alt="image" src="https://github.com/edgedb/website/assets/59022059/5ed0b54e-6b49-4867-8b9b-c0dee93383ea">

**Comment by Dhghomon** [comment]
Thanks for noticing this! Ended up proofreading the page while I was at it.
