### ISSUE TITLE
Grammar errors in the tutorial

### ISSUE THREAD

**Issue by ExAtom** [edgedb/website#7]
I found a few while reading:

- https://www.edgedb.com/tutorial/building-blocks/scalars/cal - "duraitons" instead of "durations". Also "al" instead of "all" on this same page.
- https://www.edgedb.com/tutorial/basic-queries/config/by-expression - unnecessary "the" at `...is that the it should be possible...`
- https://www.edgedb.com/tutorial/data-mutations/insert/using-for - unnecessary "the" in a comment at `...and the unpack it...`
- https://www.edgedb.com/tutorial/data-mutations/delete/deleting-data - "an an expression" instead of "as an expression"
Also an unnecessary comma on this same page at `...since it has an, exclusive constraint on it...`

**Comment by jaclarke** [comment]
Thanks for reporting these. The fixes should be live soon.
